name: "Connect to DigitalOcean K8s"
description: "Sets up kubernetes connection to DigitalOcean cluster"
inputs:
  access_token:
    description: "DigitalOcean access token"
    required: true
  cluster_name:
    description: "DigitalOcean cluster name"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.access_token }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 ${{ inputs.cluster_name }}
      shell: bash

    - name: Verify namespace exists
      run: devops namespace check --env ${{ github.ref_name }}
      shell: bash
